name: Frontend CI

on: [push]

jobs:
  runs-on: [self-hosted]
  steps:
  - uses: actions/checkout@v2
  - uses: actions/setup-node@v2
    with:
      node-version: '14'

  - name: Test & Lint react
    run: |
      npm i
      npm test
      npm run build
      npm run check-code
      npm run eslint-prettier-conflicts
      npm run stylelint-prettier-conflicts